import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
//Roboto_Mono
const inter = Inter({ subsets: ['latin']})
const robotoMono = Roboto_Mono({ subsets: ['latin'] , variable: '--font-roboto-mono'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <style>
        {`
          :root {
            --font-roboto-mono: ${robotoMono.style.fontFamily};
          }
        `}
      </style>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
